

/GunParameter/gunOptionPosition default
#/GunParameter/randomMaxPosition 0.2

#/GunParameter/gunOptionMomentum solidAngle
#/GunParameter/gunOptionMomentum gaus
/GunParameter/gunOptionMomentum fix
#/GunParameter/solidAngleX0 1.0
#/GunParameter/solidAngleRad 0.8
#/GunParameter/gaussianMean 0.0
#/GunParameter/gaussianSigma 0.2
#/GunParameter/uniformParameter 0.3


/geometry/test/grid_test true

/gun/particle gamma
/gun/energy 661.7 keV
/run/beamOn 10000
